name: AlwaysDay
version: 0.1-BETA
main: xyz.jesseke55.AlwaysDay.Main
website: www.jesseke55.xyz
authors: [jesseke55, ProtocollWeb]
commands:
    alwaysday:
      usage: /<command>
      aliases: [day4ever]
      description: The main command
    alwaysreload:
      usage: /<command>
      description: Reload the config
      aliases: [day4reload]